version: "3"

services:
  frontend:
    build:
        context: ./
    networks:
      - default
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.pixelswap-frontend.rule: "Host(`test.${DOCKER_DOMAIN}`)"
      traefik.http.routers.pixelswap-frontend.entrypoints: "web, websecure"
    restart: ${DOCKER_RESTART}

networks: 
  web:
    external: true
